name: gps_attendance
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  cloud_firestore: ^5.6.2
  dio: ^5.7.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter_bloc: ^9.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  get_it: ^8.0.3
  font_awesome_flutter: ^10.8.0
  flutter:
    sdk: flutter
  firebase_database: ^11.3.4
  syncfusion_flutter_calendar: ^28.2.9
  intl: ^0.19.0
  equatable: ^2.0.7
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/translations/en.json
    - assets/translations/ar.json
    # - data_source/gov_data.json
    # - data_source/places_data.json
# fonts:
#   - family: PlaywriteAUSA
#     fonts:
#       - asset: fonts/PlaywriteAUSA/PlaywriteAUSA-Regular.ttf

#   - family: Bitter
#     fonts:
#       - asset: fonts/Bitter/Bitter-Regular.ttf
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-VariableFont_opsz,wght.ttf
          style: normal

        - asset: assets/fonts/inter/static/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/static/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/static/Inter_18pt-Medium.ttf
          weight: 500

        - asset: assets/fonts/inter/static/Inter_24pt-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/static/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/static/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/static/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/static/Inter_24pt-Medium.ttf
          weight: 500

        - asset: assets/fonts/inter/static/Inter_28pt-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/static/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/static/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/static/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/static/Inter_28pt-Medium.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
