name: gps_attendance
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.2
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/en.json
    - assets/translations/ar.json
    # - data_source/gov_data.json
    # - data_source/places_data.json

# fonts:
#   - family: PlaywriteAUSA
#     fonts:
#       - asset: fonts/PlaywriteAUSA/PlaywriteAUSA-Regular.ttf
#   - family: Bitter
#     fonts:
#       - asset: fonts/Bitter/Bitter-Regular.ttf
