// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsquWUJDJoQfUplRo_mfzb-CveBwo-brI',
    appId: '1:453907172022:web:559749a28d98d880207417',
    messagingSenderId: '453907172022',
    projectId: 'gps-attendance-25',
    authDomain: 'gps-attendance-25.firebaseapp.com',
    storageBucket: 'gps-attendance-25.firebasestorage.app',
    measurementId: 'G-GS6WJVPRJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXKpNulqZVzgvHIPpB3ZdbxbxUUxnSTrU',
    appId: '1:453907172022:android:4fa716be7a61321d207417',
    messagingSenderId: '453907172022',
    projectId: 'gps-attendance-25',
    databaseURL: 'https://gps-attendance-25-default-rtdb.firebaseio.com',
    storageBucket: 'gps-attendance-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZdmkWGr5oknBM5NwNhXKfkmVGWpGDhI',
    appId: '1:453907172022:ios:15c7eef11a010b35207417',
    messagingSenderId: '453907172022',
    projectId: 'gps-attendance-25',
    databaseURL: 'https://gps-attendance-25-default-rtdb.firebaseio.com',
    storageBucket: 'gps-attendance-25.firebasestorage.app',
    iosBundleId: 'com.example.gpsAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdZdmkWGr5oknBM5NwNhXKfkmVGWpGDhI',
    appId: '1:453907172022:ios:15c7eef11a010b35207417',
    messagingSenderId: '453907172022',
    projectId: 'gps-attendance-25',
    storageBucket: 'gps-attendance-25.firebasestorage.app',
    iosBundleId: 'com.example.gpsAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsquWUJDJoQfUplRo_mfzb-CveBwo-brI',
    appId: '1:453907172022:web:88e791c172bf7579207417',
    messagingSenderId: '453907172022',
    projectId: 'gps-attendance-25',
    authDomain: 'gps-attendance-25.firebaseapp.com',
    storageBucket: 'gps-attendance-25.firebasestorage.app',
    measurementId: 'G-QMH11LYQ4G',
  );
}